### ISSUE TITLE
setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by mowet601** [TheAlphamerc/flutter_twitter_clone#227]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building ComposeTweetImage(dirty, dependencies: [MediaQuery]):
setState() or markNeedsBuild() called during build.

This ComposeTweetPage widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: ComposeTweetPage
  dependencies: [_LocalizationsScope-[GlobalKey#fd564], _InheritedTheme, _InheritedProviderScope<ComposeTweetState?>]
  state: _ComposeTweetReplyPageState#a5376
The widget which was currently being built when the offending call was made was: ComposeTweetImage
  dirty
  dependencies: [MediaQuery]
The relevant error-causing widget was: 
  ComposeTweetImage ComposeTweetImage: flutter_twitter_clone-master/flutter_twitter_clone-master/lib/ui/page/feed/composeTweet/composeTweet.dart:517:17
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4261:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4276:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
#3      _ComposeTweetReplyPageState._onCrossIconPressed (package:flutter_twitter_clone/ui/page/feed/composeTweet/composeTweet.dart:76:5)
#4      ComposeTweetImage.build (package:flutter_twitter_clone/ui/page/feed/composeTweet/widget/composeTweetImage.dart:42:53)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4657:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4583:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5618:32)
#11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6274:17)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#15     ProxyElement.update (package:flutter/src/widgets/framework.dart:4938:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#17     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5618:32)
#18     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6274:17)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#26     StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#30     StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#45     StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#51     ProxyElement.update (package:flutter/src/widgets/framework.dart:4938:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#57     StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#67     StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#72     StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#77     StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#81     StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#83     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5618:32)
#84     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6274:17)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#88     StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#92     ProxyElement.update (package:flutter/src/widgets/framework.dart:4938:5)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#96     ProxyElement.update (package:flutter/src/widgets/framework.dart:4938:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#98     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5618:32)
#99     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6274:17)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#102    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#104    StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#108    ProxyElement.update (package:flutter/src/widgets/framework.dart:4938:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#111    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#113    StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#119    StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6120:14)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#126    StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#129    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#135    ProxyElement.update (package:flutter/src/widgets/framework.dart:4938:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#139    StatelessElement.update (package:flutter/src/widgets/framework.dart:4664:5)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#142    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#144    StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#148    ProxyElement.update (package:flutter/src/widgets/framework.dart:4938:5)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#151    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#153    StatefulElement.update (package:flutter/src/widgets/framework.dart:4790:5)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4608:16)
#156    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4758:11)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#158    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#159    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#160    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#161    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1148:15)
#162    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1084:9)
#163    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#167    _invoke (dart:ui/hooks.dart:166:10)
#168    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#169    _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
===================================================================================================
![Screenshot_20211221-145654_(1)](https://user-images.githubusercontent.com/4493458/146996990-a5cc769b-b42d-4cd1-a3c7-7f2f1e430dbe.png)
=

**Comment by rahilhussain** [comment]
yes,i got the same issue,@alphamerc please answer this query

**Comment by rahilhussain** [comment]
@TheAlphamerc please suggest the solution bro.@Omorian if you got solution reply to this

**Comment by TheAlphamerc** [comment]
@rahilhussain Let me know on which screen you got this error ?

**Comment by rahilhussain** [comment]
When I'm trying to upload picture in a tweet I'm getting this error message.
Also my firestore database is empty.

**Comment by rahilhussain** [comment]
When I'm trying to upload picture in a tweet I'm getting this error message.
Also my firestore database is showing empty.

![Screenshot_2022-01-03-15-25-48-72_7637f96361ee2923e29308a51b06c214.png](https://user-images.githubusercontent.com/53215621/148021623-c45de45d-3898-4ec2-ba33-a672c0230a79.png)

**Comment by rahilhussain** [comment]
@TheAlphamerc also there's a glitch while commenting on a tweet. It'll be Highly appreciable, if you kindly solve these queries🤞

**Comment by TheAlphamerc** [comment]
This might be happening because of null safety migration. I'll look into it.

**Comment by rahilhussain** [comment]
Also my firestore db showing empty. There's  also glitch in commenting on
tweets. Please look into it.

**Comment by TheAlphamerc** [comment]
@mowet601 @rahilhussain  Issue is fixed.

**Comment by rahilhussain** [comment]
@TheAlphamerc thank you.

These are three issues that I've identified,if possible please suggesest solutions to following queries:
1)Comment glitch -> after commenting on a tweet, it's getting added to database in backend but loading infinitely on frontend.
2)Multiple sign-in error -> if i sign in with another google account,tweets are not loading at all.
3)Share link/Share on social media button & in-browser feature for external links are not working.

**Comment by rahilhussain** [comment]
@TheAlphamerc   thank you.  If you provide the solutions for following problems it'll greately helpful for the people who're using your repository.Please Look into following queries.

These are three issues that I've identified,if possible please suggesest solutions to following queries:
1)Comment glitch -> after commenting on a tweet, it's getting added to database in backend but loading infinitely on frontend.
![image](https://user-images.githubusercontent.com/53215621/148647148-cc8dc484-0241-4e01-bd91-0101dd5edb44.png)

2)Multiple sign-in with google error -> if i sign in with another google account,I'm unable to follow any one,if i try i'm getting the following error given in screenshot. tweets are not loading at all.

![image](https://user-images.githubusercontent.com/53215621/148647249-003a8c81-e287-4368-adac-b6fcbe193f03.png)

3)Share button -> Share link/Share on social media button not working,if i try i'm getting the following error given in screenshot.

![image](https://user-images.githubusercontent.com/53215621/148647440-e72188ef-8538-4bbe-965f-8d50c17bc124.png)
