### ISSUE TITLE
Error in composeTweet section

### ISSUE THREAD

**Issue by imDarkceus** [TheAlphamerc/flutter_twitter_clone#255]
after writing a caption and selecting an image when i click on Tweet button to post my tweet it shows error in console and the loading icon is continuously spinning.

The error:
E/flutter ( 4210): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 4210): #0      _ComposeTweetReplyPageState.createTweetModel (package:flutter_twitter_clone/ui/page/feed/composeTweet/composeTweet.dart:168:28)
E/flutter ( 4210): #1      _ComposeTweetReplyPageState._submitButton (package:flutter_twitter_clone/ui/page/feed/composeTweet/composeTweet.dart:96:34)
E/flutter ( 4210): #2      CustomAppBar._getActionButtons.<anonymous closure> (package:flutter_twitter_clone/widgets/customAppBar.dart:90:64)
E/flutter ( 4210): #3      OnPressed.ripple.<anonymous closure> (package:flutter_twitter_clone/ui/theme/extention.dart:36:30)
E/flutter ( 4210): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter ( 4210): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter ( 4210): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
E/flutter ( 4210): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter ( 4210): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter ( 4210): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
E/flutter ( 4210): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
E/flutter ( 4210): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
E/flutter ( 4210): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
E/flutter ( 4210): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
E/flutter ( 4210): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
E/flutter ( 4210): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter ( 4210): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter ( 4210): #17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
E/flutter ( 4210): #18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter ( 4210): #19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter ( 4210): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter ( 4210): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter ( 4210): #22     _rootRunUnary (dart:async/zone.dart:1444:13)
E/flutter ( 4210): #23     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4210): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4210): #25     _invoke1 (dart:ui/hooks.dart:169:10)
E/flutter ( 4210): #26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
E/flutter ( 4210): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
E/flutter ( 4210): 
W/ActivityThread( 4210): SCHED: com.nexa.twrt/com.thealphamerc.flutter_twitter_clone.MainActivity [80, r=10060ms, a=2396ms, w=309996ms]

**Comment by ericlchen369** [comment]
im having the same error...

below is my flutter doctor output: 

[✓] Flutter (Channel unknown, 2.10.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.10.0 at /Users/mreric/Documents/Projects/development/flutter
    • Upstream repository unknown
    • Framework revision 5f105a6ca7 (4 months ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/mreric/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/mreric/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by TheAlphamerc** [comment]
Just checked the create tweet functionality and it is working fine. Maybe the issue you are facing is causing due to some special use cases. Or if you can share the steps to reproduce the issue will help me identify the root cause.
