### ISSUE TITLE
Unable to Run the Project 

### ISSUE THREAD

**Issue by isidorodasilva** [TheAlphamerc/flutter_twitter_clone#270]
Hi,
I have cloned the project and when I try to run the flowing is showing, please advise

**Android or IOS Build** 
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1

**And Web Build** 
Waiting for connection from debug service on Chrome...
../../.pub-cache/hosted/pub.dartlang.org/link_preview_generator-1.2.0/lib/src/rules/default.scrapper.dart:128:19: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
          if (img.naturalWidth! > img.naturalHeight!) {
                  ^
../../.pub-cache/hosted/pub.dartlang.org/link_preview_generator-1.2.0/lib/src/rules/default.scrapper.dart:128:39: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
          if (img.naturalWidth! > img.naturalHeight!) {
                                      ^
../../.pub-cache/hosted/pub.dartlang.org/link_preview_generator-1.2.0/lib/src/rules/default.scrapper.dart:130:21: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
            if (img.naturalWidth! / img.naturalHeight! > 3) {
                    ^
../../.pub-cache/hosted/pub.dartlang.org/link_preview_generator-1.2.0/lib/src/rules/default.scrapper.dart:130:41: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
            if (img.naturalWidth! / img.naturalHeight! > 3) {
                                        ^
../../.pub-cache/hosted/pub.dartlang.org/link_preview_generator-1.2.0/lib/src/rules/default.scrapper.dart:135:21: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
            if (img.naturalHeight! / img.naturalWidth! > 3) {
                    ^
../../.pub-cache/hosted/pub.dartlang.org/link_preview_generator-1.2.0/lib/src/rules/default.scrapper.dart:135:42: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
            if (img.naturalHeight! / img.naturalWidth! > 3) {
                                         ^
../../.pub-cache/hosted/pub.dartlang.org/link_preview_generator-1.2.0/lib/src/rules/default.scrapper.dart:140:19: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
          if (img.naturalHeight! <= 50 || img.naturalWidth! <= 50) {
                  ^
../../.pub-cache/hosted/pub.dartlang.org/link_preview_generator-1.2.0/lib/src/rules/default.scrapper.dart:140:47: Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
          if (img.naturalHeight! <= 50 || img.naturalWidth! <= 50) {
                                              ^
This app is linked to the debug service: ws://127.0.0.1:49854/vqnakPlMVEE=/ws
Debug service listening on ws://127.0.0.1:49854/vqnakPlMVEE=/ws

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:49854/vqnakPlMVEE=/ws
Flutter Web Bootstrap: Auto
Error: Assertion failed: file:///Users/macbookpro/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.6.5/lib/src/firebase_core_web.dart:273:11
options != null
"FirebaseOptions cannot be null when creating the default app."
    at Object.throw_ [as throw] (http://localhost:49755/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:49755/dart_sdk.js:5005:15)
    at firebase_core_web.FirebaseCoreWeb.new.initializeApp (http://localhost:49755/packages/firebase_core_web/firebase_core_web.dart.lib.js:252:42)
    at initializeApp.next (<anonymous>)
    at http://localhost:49755/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:49755/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:49755/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:49755/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:49755/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:49755/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49755/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:49755/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:49755/dart_sdk.js:40784:13)
    at http://localhost:49755/dart_sdk.js:36261:9

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**App**
- version[e.g.  1.0.4]

**Additional context**

**Comment by adilwahla** [comment]
Hey update packages versions and solve issues if you encountered any

**Comment by TheAlphamerc** [comment]
@isidorodasilva if you are still facing the issue please run flutter clean command and get packages.
