### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by terzux** [TheAlphamerc/flutter_twitter_clone#274]
okay so I was successfully able to install the packages and everything but after the app is been installed while on the debug mode, it unexpectedly closes. Please can someone help me on how to fix this?

 - Device: Infinix Hot 8
 - OS: Android
 - Version 8

**Comment by TheAlphamerc** [comment]
@terzux Please make sure you have integrated the firebase correctly and configured firebase auth, database and storage.

**Comment by terzux** [comment]
`E/AndroidRuntime(21850): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.friendszone.chat.MainActivity" on path: DexPathList[[zip file "/data/app/com.friendszone.chat-9vE_LiYDxZfSTVrrtUo9-A==/base.apk"],nativeLibraryDirectories=[/data/app/com.friendszone.chat-9vE_LiYDxZfSTVrrtUo9-A==/lib/arm, /data/app/com.friendszone.chat-9vE_LiYDxZfSTVrrtUo9-A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
E/AndroidRuntime(21850): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/AndroidRuntime(21850): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(21850): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(21850): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
E/AndroidRuntime(21850): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2710)
E/AndroidRuntime(21850): 	... 9 more`

It is still crashes on opening. Here is the logs

**Comment by TheAlphamerc** [comment]
> com.friendszone.chat.MainActivity



> `E/AndroidRuntime(21850): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.friendszone.chat.MainActivity" on path: DexPathList[[zip file "/data/app/com.friendszone.chat-9vE_LiYDxZfSTVrrtUo9-A==/base.apk"],nativeLibraryDirectories=[/data/app/com.friendszone.chat-9vE_LiYDxZfSTVrrtUo9-A==/lib/arm, /data/app/com.friendszone.chat-9vE_LiYDxZfSTVrrtUo9-A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]] E/AndroidRuntime(21850): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125) E/AndroidRuntime(21850): at java.lang.ClassLoader.loadClass(ClassLoader.java:379) E/AndroidRuntime(21850): at java.lang.ClassLoader.loadClass(ClassLoader.java:312) E/AndroidRuntime(21850): at android.app.Instrumentation.newActivity(Instrumentation.java:1174) E/AndroidRuntime(21850): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2710) E/AndroidRuntime(21850): ... 9 more`
> 
> It is still crashes on opening. Here is the logs

By seeing activity log I think you have modified the code and maybe this is causing the issue.
