### ISSUE TITLE
Remote config issue

### ISSUE THREAD

**Issue by Pratip009** [TheAlphamerc/flutter_twitter_clone#301]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 87)
E/flutter (13496): ...uild Version>","          "versions": [ <Current Build Version> ]       } }
E/flutter (13496):                               ^
E/flutter (13496):
E/flutter (13496): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter (13496): #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:913:48)
E/flutter (13496): #2      _parseJson (dart:convert-patch/convert_patch.dart:35:10)

I have updated the appversion in firebase but still getting this error. please help

**Comment by TheAlphamerc** [comment]
@Pratip009  Can you share the firebase Remote config screenshot that you added?
